### ISSUE TITLE
issue building v1.5.3

### ISSUE THREAD

**Issue by roboto-cloud** [reactioncommerce/base#6]
Someone know how fix it?

**steps:**

- git clone https://github.com/reactioncommerce/reaction.git && cd reaction
- yarn install
- docker build --build-arg TOOL_NODE_FLAGS="--max-old-space-size=4096" -t me/reaction:v1.5.3 .

```
The command '/bin/sh -c cd $APP_SOURCE_DIR &&             $BUILD_SCRIPTS_DIR/install-deps.sh &&             $BUILD_SCRIPTS_DIR/install-node.sh &&             $BUILD_
SCRIPTS_DIR/install-phantom.sh &&             $BUILD_SCRIPTS_DIR/install-mongo.sh &&             $BUILD_SCRIPTS_DIR/install-meteor.sh &&             $BUILD_SCRIPTS_D
IR/build-meteor.sh &&             $BUILD_SCRIPTS_DIR/post-build-cleanup.sh' returned a non-zero code: 1
```

```
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.1.1 (node_modules/sane/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

[-] Building Meteor application...


Even with METEOR_ALLOW_SUPERUSER or --allow-superuser, permissions in your app
directory will be incorrect if you ever attempt to perform any Meteor tasks as
a normal user. If you need to fix your permissions, run the following command
from the root of your project:

  sudo chown -Rh <username> .meteor/local

{ [Error: ENOSPC: no space left on device, unlink '/tmp/mt-15433ki/npm/node_modules/rx-lite/.meteor-portable']
  errno: -28,
  code: 'ENOSPC',
  syscall: 'unlink',
  path: '/tmp/mt-15433ki/npm/node_modules/rx-lite/.meteor-portable' }
/root/.meteor/packages/meteor-tool/.1.5.2_2.fkst7p++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/meteor-promise/promise_ser
ver.js:218
      throw error;
      ^

Error: failed to make temporary directory in /tmp
    at make (/tools/fs/files.js:673:11)
    at Object.files.mkdtemp (/tools/fs/files.js:675:13)
    at Object.exports._extractAndConvert (/tools/packaging
```

**Comment by jshimko** [comment]
`Error: ENOSPC: no space left on device`

The Docker build ran out of disk space.  Try cleaning up unused images or cached layers from other builds.
